---
# This playbook deploys the whole application stack in this site.  

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: vagrant
  become: yes
  become_method: su

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: vagrant
  become: yes
  become_method: su

  roles:
    - db
